/**
 *
 * @author Viruz
 */
public class Cronometro extends javax.swing.JFrame {
    CronometroThread cronometro;
    Object source;
    
    /**
     * Creates new form Cronometro
     */
    public Cronometro() {
        initComponents();
        cronometro = new CronometroThread(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        start = new javax.swing.JButton();
        pause = new javax.swing.JButton();
        bcontinue = new javax.swing.JButton();
        stop = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        display = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Viruz Blog: Cronometro");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 45));

        start.setText("Iniciar");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        jPanel1.add(start);

        pause.setText("Pause");
        pause.setEnabled(false);
        pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseActionPerformed(evt);
            }
        });
        jPanel1.add(pause);

        bcontinue.setText("Continuar");
        bcontinue.setEnabled(false);
        bcontinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcontinueActionPerformed(evt);
            }
        });
        jPanel1.add(bcontinue);

        stop.setText("Detener");
        stop.setEnabled(false);
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });
        jPanel1.add(stop);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 130));
        jPanel2.setLayout(new java.awt.BorderLayout());

        display.setFont(new java.awt.Font("Times New Roman", 0, 50)); // NOI18N
        display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        display.setText("0 : 0 : 0");
        jPanel2.add(display, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        source = evt.getSource();
        if(source == start){
                cronometro.createThread();
                cronometro.setLive(true);
                cronometro.setGo(true);
                start.setEnabled(false);
                pause.setEnabled(true);
                stop.setEnabled(true);
       }
    }//GEN-LAST:event_startActionPerformed

    private void pauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseActionPerformed
            pause.setEnabled(false);
            bcontinue.setEnabled(true);
            cronometro.suspenderThread();
    }//GEN-LAST:event_pauseActionPerformed

    private void bcontinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcontinueActionPerformed
            pause.setEnabled(true);            
            cronometro.continuarThread();
            bcontinue.setEnabled(false);
    }//GEN-LAST:event_bcontinueActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
            start.setEnabled(true);
            stop.setEnabled(false);
            pause.setEnabled(false);
            cronometro.setLive(false);
            cronometro.setGo(false);
            cronometro.setSegundos(0);
    }//GEN-LAST:event_stopActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcontinue;
    private javax.swing.JLabel display;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton pause;
    private javax.swing.JButton start;
    private javax.swing.JButton stop;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the display
     */
    public javax.swing.JLabel getDisplay() {
        return display;
    }

    /**
     * @param display the display to set
     */
    public void setDisplay(javax.swing.JLabel display) {
        this.display = display;
    }
}